swiftlint, code reivew시 slackbot 추가
f-lab-edu/ToDoGeo pull request #11
Opened 2024-05-16 14:15 UTC by gguming

# 무엇에 관한 pr인가요?
- #10 ci 관련한 pr 입니다.

## swiftlint
- pr시 swift lint를 적용하도록 swiftlint.yml 파일을 추가했습니다.

##slack bot
- code review가 완료되면 slack에 알림을 줄 수 있도록 pull-request-slack-bot.yml파일을 추가했습니다.
- approve: 성공, Request changes: 실패 관련 메시지를 슬랙에 보냅니다.
- 리뷰 코멘트가 달렸을 경우 코멘트 확인 안내 메시지를 슬랙에 보냅니다.

2024-05-18 14:21 UTC, sqlpro requested changes
Slack 알림에 대한 CI용 대상 브랜치가 `main`으로 설정되어 있는데, 요거 맞는 건지 확인 한번 해주세요~

2024-05-18 14:21 UTC, sqlpro commented on .github/workflows/pull-request-slack-bot.yml
> +    branches: [main]
음.. 이거 브랜치가 `feature/*` 여야 하는 거 아닌가요?

2024-05-19 10:31 UTC, gguming commented on .github/workflows/pull-request-slack-bot.yml
> +    branches: [main]
[1f71f37] 수정된 커밋입니다.

2024-05-21 23:12 UTC, gguming commented on .github/workflows/pull-request-slack-bot.yml
> +    branches: [main]
테스트 메시지

2024-05-21 23:21 UTC, gguming commented on .github/workflows/pull-request-slack-bot.yml
> +    branches: [main]
테스트 커멘트

2024-06-02 12:21 UTC, abdul0986 approved these changes
LGTM

2024-06-03 09:00 UTC, merged