ci slack 테스트
f-lab-edu/ToDoGeo pull request #12
Opened 2024-05-21 23:04 UTC by gguming

- 테스트

2024-06-02 12:28 UTC, abdul0986 commented on .github/workflows/pull-request-slack-bot.yml
> +      - 'feature/*'
[테스트]: 조건문을 다시 확인해주세요

2024-06-02 12:37 UTC, gguming commented
[테스트]

2024-06-02 12:38 UTC, abdul0986 commented
;;;;

2024-06-02 12:41 UTC, abdul0986 requested changes
Request Changes

2024-06-02 12:41 UTC, abdul0986 commented on .github/workflows/pull-request-slack-bot.yml
> +  pull_request_review:
[테스트]

2024-06-02 12:41 UTC, abdul0986 commented on .github/workflows/pull-request-slack-bot.yml
> +          text: '코드 리뷰가 성공적으로 승인되었습니다.'
코멘트 테스트

2024-06-02 12:42 UTC, abdul0986 commented on .github/workflows/swiftlint.yml
> +      - '**/*.swift'
[Test] Single Comment

2024-06-02 12:47 UTC, abdul0986 commented on .github/workflows/pull-request-slack-bot.yml
> +      - 'feature/*'
Test Single Comment

2024-06-03 08:30 UTC, gguming commented
[테스트] comment

2024-06-03 08:31 UTC, gguming commented on .github/workflows/pull-request-slack-bot.yml
> +      - 'feature/*'
[테스트] comment

2024-06-03 08:41 UTC, gguming commented
[테스트] comment

2024-06-03 08:45 UTC, gguming commented
테스트 테스트

2024-06-03 08:49 UTC, gguming reviewed
pull request 추가

2024-06-03 08:50 UTC, gguming commented
[테스트] 코멘트 코멘트

2024-06-03 08:50 UTC, gguming commented
[테스트] 코멘트 코멘트

2024-06-03 08:51 UTC, gguming reviewed
테스트

2024-06-03 08:54 UTC, gguming reviewed
pull request  수정

2024-06-03 08:58 UTC, gguming reviewed
[테스트]

2024-06-03 08:59 UTC, closed without merging