투두 리스트 map에 보여주는 기능
f-lab-edu/ToDoGeo pull request #21
Opened 2024-07-15 15:18 UTC by gguming

[#20] ToDo map에 보여주는 기능입니다. 

<img src="https://github.com/user-attachments/assets/b52b2690-c2e1-44c0-81fe-79f8fd8c119f" width="585" height="1266"/>

# 추가 기능
- 처음 진입 시 현재 위치가 지도 center
- 지도 화면에 불러온 ToDo가 pin으로 보임
- ToDo 추가 시 자동으로 업데이트

2024-07-16 14:36 UTC, abdul0986 requested changes
피드백 반영 부탁드립니다.

2024-07-16 14:36 UTC, abdul0986 commented on ToDoGeo/Entity/Todo/ToDo.swift
> +            "locationName": locationName
전반적으로 네이밍 길이를 콤팩트하게 선정하면 좋겠습니다. 

1. toDictionary() -> toDict()
2. latitude -> lat 
3. longitude -> lng 
4. locationName -> locName 
5. location -> loc

2024-07-16 14:36 UTC, abdul0986 commented on ToDoGeo/Repository/Protocol/ToDoRepositoryProtocol.swift
> +    func addToDo(_ todo: ToDo) -> Observable<Void>
```suggestion
    func add(_ item: ToDo) -> Observable<Void>
```

`ToDo`가 반복되고 있어서, 불필요하게 중복되는 부분은 걷어내는 게 좋을 듯 합니다.

2024-07-16 14:36 UTC, abdul0986 commented on ToDoGeo/Repository/Protocol/ToDoRepositoryProtocol.swift
> +    func getToDos() -> Observable<[ToDo]>
```suggestion
    func getList() -> Observable<[ToDo]>
```

`getToDos()`보다는 `getList`가 어떨까 합니다.

2024-07-16 14:36 UTC, abdul0986 commented on ToDoGeo/Repository/ToDoMapsReactor.swift
> +extension ToDoMapsReactor {
요 컨벤션이 존재하는 컨벤션인가요? 링크 첨부 부탁드려요

2024-07-16 14:36 UTC, abdul0986 commented on ToDoGeo/Repository/ToDoMapsReactor.swift
> +            })
```suggestion
            .map($0)
```
이런 식으로 쓸 수 있지 않을까요?

2024-07-16 14:36 UTC, abdul0986 commented on ToDoGeo/Repository/ToDoMapsViewController.swift
> +    }
`UIViewController override function`들은 별도의 extention으로 분리해서 처리하는 게 깔끔합니다.

2024-07-16 14:36 UTC, abdul0986 commented on ToDoGeo/Repository/ToDoRepository.swift
> +            guard let userId = Auth.auth().currentUser?.uid  else {
```suggestion
            guard let userId = Auth.auth().currentUser?.uid else {
```

2024-07-16 14:36 UTC, abdul0986 commented on ToDoGeo/Repository/ToDoRepository.swift
> +    func getToDos() -> Observable<[ToDo]> {
```suggestion
    func getList() -> Observable<[ToDo]> {
```

2024-07-16 14:36 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Common/Resource/GoogleService-Info.plist
>  </plist>
EOL 넣어주세요

2024-07-16 14:36 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Location/LocationManger.swift
> +        }
```
if let region = locationManager.monitoredRegions.findFirstMatching({ $0.identifier == id }) {
   ...
}
```
filter.first 체인으로 엮기보다는 위와 같이 적절한 함수로 변경하기를 권장합니다.

2024-07-16 14:36 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Main/ToDo/AddToDoReactor.swift
> +            } else if newState.toDo.title.count > 15 {
15가 자주 등장하는 사이즈인데, 상수화했으면 합니다.

2024-07-17 14:41 UTC, gguming commented on ToDoGeo/Repository/ToDoMapsReactor.swift
> +extension ToDoMapsReactor {
해당 컨벤션은 따로 찾아보지는 않았습니다. 개인적으로 extention에 private가 좀 더 잘 보이는 것 같아 저렇게 사용하고 있었습니다.

2024-07-17 14:56 UTC, gguming commented on ToDoGeo/ToDoGeo/Common/Resource/GoogleService-Info.plist
>  </plist>
EOL이 무엇인가요? 검색해본 결과 여러 의미가 있지만 추측 상 end of line 같은데 이게 맞다면 어떤 방식으로 줄바꿈을 해야하나요?
단어가 제 추측과 다른 뜻이라면 어떤식으로 수정해야하나요?

2024-07-17 14:59 UTC, gguming commented on ToDoGeo/ToDoGeo/Location/LocationManger.swift
> +        }
해당 기능이 없습니다!

2024-07-17 15:05 UTC, gguming commented on ToDoGeo/Entity/Todo/ToDo.swift
> +            "locationName": locationName
[24c2cae](https://github.com/f-lab-edu/ToDoGeo/pull/21/commits/24c2caec6d1c16949f5d17db7d58f7fdd31fa774) 수정한 커밋입니다.

2024-07-17 15:05 UTC, gguming commented on ToDoGeo/Repository/Protocol/ToDoRepositoryProtocol.swift
> +    func addToDo(_ todo: ToDo) -> Observable<Void>
[24c2cae](https://github.com/f-lab-edu/ToDoGeo/pull/21/commits/24c2caec6d1c16949f5d17db7d58f7fdd31fa774) 수정한 커밋입니다.

2024-07-17 15:06 UTC, gguming commented on ToDoGeo/Repository/Protocol/ToDoRepositoryProtocol.swift
> +    func getToDos() -> Observable<[ToDo]>
[24c2cae](https://github.com/f-lab-edu/ToDoGeo/pull/21/commits/24c2caec6d1c16949f5d17db7d58f7fdd31fa774) 수정한 커밋입니다.

2024-07-17 15:06 UTC, gguming commented on ToDoGeo/Repository/ToDoMapsReactor.swift
> +extension ToDoMapsReactor {
[10a959d](https://github.com/f-lab-edu/ToDoGeo/pull/21/commits/10a959d4f8767d4f2b5632c27cc927a45381fc2b) 수정한 커밋입니다.

2024-07-17 15:07 UTC, gguming commented on ToDoGeo/Repository/ToDoMapsReactor.swift
> +            })
[2d4a1d8](https://github.com/f-lab-edu/ToDoGeo/pull/21/commits/2d4a1d880219535bc6fd331769555c451f451eb4) 수정한 커밋입니다.

2024-07-17 15:07 UTC, gguming commented on ToDoGeo/Repository/ToDoMapsViewController.swift
> +    }
[250e24c](https://github.com/f-lab-edu/ToDoGeo/pull/21/commits/250e24c8aade15b487ceee31ff50fabe0bf97c68) 수정한 커밋입니다.

2024-07-17 15:08 UTC, gguming commented on ToDoGeo/Repository/ToDoRepository.swift
> +            guard let userId = Auth.auth().currentUser?.uid  else {
[3895214](https://github.com/f-lab-edu/ToDoGeo/pull/21/commits/38952142bec005ff39fe14bcc6d157ebb0fbfc95) 수정한 커밋입니다.

2024-07-17 15:09 UTC, gguming commented on ToDoGeo/Repository/ToDoRepository.swift
> +    func getToDos() -> Observable<[ToDo]> {
[24c2cae](https://github.com/f-lab-edu/ToDoGeo/pull/21/commits/24c2caec6d1c16949f5d17db7d58f7fdd31fa774) 수정한 커밋입니다.

2024-07-17 15:09 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Main/ToDo/AddToDoReactor.swift
> +            } else if newState.toDo.title.count > 15 {
[b701fef](https://github.com/f-lab-edu/ToDoGeo/pull/21/commits/b701fefc748d220e3d91a2d940c26d848488fdb9) 수정한 커밋입니다.

2024-07-18 11:22 UTC, gguming commented on ToDoGeo/ToDoGeo/Common/Resource/GoogleService-Info.plist
>  </plist>
[49f29a2](https://github.com/f-lab-edu/ToDoGeo/pull/21/commits/49f29a24032761f8100c55b0df34a9d604a58860) 수정한 커밋입니다.

2024-07-21 12:24 UTC, abdul0986 approved these changes
LGTM

2024-07-22 01:51 UTC, merged