[#1] 프로젝트 초기 설정
f-lab-edu/ToDoGeo pull request #3
Opened 2024-04-14 14:11 UTC by gguming

## 의존성 관리 SPM 설정
- 사용할 라이브러리 SPM에 추가(ReactorKit, RxSwift)

## 스토리보드 삭제 및 코드 베이스 UI 구축
- 초기 생성된 스토리보드를 삭제하고 코드로 UI를 구성 할 수 있도록 세팅. 임시로 ViewController로 초기화면 설정

## BaseViewController 추가
- UIViewController에서 공통적으로 적용할 기능을 담은 BaseViewController 추가
- 앞으로 추가할 ViewController에 상속해서 사용할 예정입니다.

## Clean Arcitecture 적용을 위한 폴더 구조
- 폴더 구조를 만들고 레이어를 구분했습니다.
- 레이어에 대한 정보는 Readme에 추가했습니다.
<img width="268" alt="image" src="https://github.com/f-lab-edu/ToDoGeo/assets/72551674/aa64e21f-6cb1-4e0e-b877-1e8983338ac7">

2024-04-14 14:12 UTC, abdul0986 commented
Good Job

2024-04-14 14:22 UTC, abdul0986 requested changes
피드백 검토 부탁드립니다.

2024-04-14 14:22 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/ViewController.swift
PR에 필요하지 않은, 역할이 없는 클래스 같습니다. 
삭제 부탁드립니다.

2024-04-21 11:54 UTC, gguming commented on ToDoGeo/ToDoGeo/ViewController.swift
be92abf
해당 커밋에 적용했습니다

2024-04-21 12:28 UTC, gguming commented
[#2] 브랜치를 나누지 않고 바로 작업하다 보니다 테그된 작업까지 같이 작업했습니다.

![image](https://github.com/f-lab-edu/ToDoGeo/assets/72551674/ca0101f0-7e6e-4781-8d26-6b9af0de68dd)

## Flows
- RxFlow 라이브러리를 이용하여 화면 이동 로직을 담당하는 파트입니다.
- Flow 파일 : 도메인마다 화면 처리를 할 수 있도록 나눴습니다.(SingInFlow, ToDoFlow) 
- AppStepper 파일 : AppFlow파일에서 초기에 어떤 화면으로 갈지 설정하게 되는데 해당 초기값을 설정을 위해 추가했습니다.
- AppStep 파일 : 화면 전환에 대한 각 케이스를 담고있는 파일입니다.
- 각 화면마다 화면 이동 로직을 Flow 인스턴스로 호출을 담당하는 인스턴스가 필요하고 해당 기능을 담당하기 위해서는 Stepper라는 protocol을 준수해야 합니다. 이 기능을 화면에서 담당 할 수도 있고, Reactor에서도 담당 할 수 있지만 저는 Reactor에서 처리하도록 결정했고, 각 화면마다 대응하는 Reactor 인스턴스를 추가하고 Stepper protocol을 준수하도록 했습니다.

2024-04-21 14:21 UTC, abdul0986 requested changes
피드백 반영 부탁드립니다.

2024-04-21 14:21 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Base/BaseViewController.swift
> +    var disposeBag: DisposeBag = DisposeBag()
1. `let` or `var` 기준이 명확하지 않을 때에는 우선 `let`으로 선언해 두도록 합니다. 
2. 타입 선언이 반드시 필요한 경우가 아닐 때에는 생략해주세요

2024-04-21 14:21 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Base/BaseViewController.swift
> +    func setupAttribute() {}
빈 함수를 두는 것은 좋지 않아 보입니다. 제거하고, Protocol / Extension 등을 이용하도록 코드를 리팩토링해 주세요

2024-04-21 14:21 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/AppFlow.swift
> +        }
해당 코드가 객체 지향 원칙 중에서 OCP 원칙을 위배할 가능성이 높아 보입니다. 리팩토링을 검토해주세요 (당장은 적용하지 않아도 무방)

2024-04-21 14:21 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/AppFlow.swift
> +extension AppFlow {
`///MARK: - ` 주석으로 구분해주세요

2024-04-21 14:21 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/AppStep.swift
설명이나 주석이 들어가야 할 것 같습니다.

2024-04-23 14:07 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Base/BaseViewController.swift
> +    var disposeBag: DisposeBag = DisposeBag()
[6262dd6] 수정한 커밋입니다.

2024-04-23 14:08 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Base/BaseViewController.swift
> +    func setupAttribute() {}
[e0f501d] 수정한 커밋입니다.

2024-04-23 14:09 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/AppFlow.swift
> +extension AppFlow {
[13e57f2] 수정한 커밋입니다.

2024-04-23 14:17 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/AppStep.swift
[9b33e3f] 수정한 커밋입니다

2024-04-27 06:54 UTC, abdul0986 requested changes
지난 번 피드백은 모두 잘 반영되었네요. 
추가 피드백이 있는데, 내용 확인해주시고 내일 멘토링 전에 모두 적용 가능하실지 검토해주세요.

2024-04-27 06:54 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Base/BaseViewController.swift
> +
여기 공백이 어떤 Code Convention에 따른 것인가요? Code Convention에 따른 것이 아니라면 요 빈 라인은 삭제해주시면 좋겠습니다.

2024-04-27 06:54 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/AppStep.swift
> +}
의미 구분을 위해서 `signInXXX` 시리즈와 `toDoXXX` 시리즈로 나누면서 중간에 공백을 집어넣으신 것이라고 하셨죠? 그렇다면 `//MARK: - ` 주석도 함께 넣어주시면 좋겠습니다.

2024-04-27 06:54 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/AppFlow.swift
> +// MARK: 화면 이동 로직
표준은 `//MARK:` 처럼 중간에 공백을 두지 않는 것입니다. 
이외에도 유의미한 역할을 하는 Code Organise Comment 시리즈가 많습니다. 읽어보시고, 가능한 부분에 적용해보시길 권장드려요. 

https://medium.com/@alexbeon22/organise-your-swift-code-mark-4cb934b31df0

2024-04-27 06:54 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/ToDoFlow.swift
> +import UIKit
`import` 처리하는 라이브러리에도 권장 순서가 있는데요. 우선은 빌트인 되어 있는 표준 라이브러리들 부터 나열하고, 그 이후에 한 줄의 공백으로 구분하여 서드파티 라이브러리를 나열하는 것이 표준입니다. 각 그룹 내부는 ABC 순으로 나열하시면 되고요. 

적용 부탁드립니다.

2024-04-27 06:54 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/ToDoFlow.swift
> +        guard let step = step as? AppStep else { return .none }
가독성을 위해서 아래와 같이 줄바꿈 처리 부탁드립니다. 

```suggestion
        guard let step = step as? AppStep else { 
            return .none 
        }
```

2024-04-27 06:54 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Main/ToDo/ToDoReactor.swift
> +    }
앞서 보내드린 링크에, `//TODO` 주석의 표준 사용법이 있습니다. 반영 부탁드립니다. 
https://medium.com/@alexbeon22/organise-your-swift-code-mark-4cb934b31df0

2024-04-27 06:54 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/SignInFlow.swift
> +
특별한 이유가 있는 것이 아니라면 빈 라인이 두 줄 이상 들어가지 않도록 정리해주시길 요청드립니다.

2024-04-27 06:54 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/System/SceneDelegate.swift
> +        guard let windowScene = (scene as? UIWindowScene) else { return }
가독성을 위해 아래와 같이 변경 부탁드립니다. 

```suggestion
        guard let windowScene = (scene as? UIWindowScene) else { 
            return 
        }
```

2024-04-27 06:54 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/SignInFlow.swift
> +        guard let step = step as? AppStep else { return .none }
가독성을 위해서, return 구문은 줄바꿈 처리 부탁드립니다.

2024-04-27 06:54 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/SignInFlow.swift
> +        return viewController
이 부분은 아래와 같이 한 줄로 처리했어도 되었을 것 같은데요. 어떻게 생각하시나요? 

```suggestion
        return UINavigationController()
```

2024-04-27 06:54 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/SignInFlow.swift
> +            return .none
추후에 `navigation(to step: Step)`을 호출한 함수의 인자 타입이 `.signInRequired` 가 아니어서 .none을 리턴받게 되면, 어떤 일이 벌어지나요?

2024-04-27 06:54 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/SignInFlow.swift
> +            return .none
전체적으로 모든 코드에 `.default` 일 때 `return .none`을 던지도록 처리되고 있는데, 좋지 않은 구조인 것은 분명합니다. 아예 처음부터 의도하지 않은 요청이 들어오지 않을 수 있도록 걸러내야 할 것 같네요. 

Strategy Pattern이 딱 적합한 구조인데, 이 패턴은 Class 레벨로 분리하는 것을 전제로 하고 있어서.. Method 레벨에서 동작할 수 있도록 Strategy Pattern을 응용해보시죠.

2024-04-28 11:12 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/SignInFlow.swift
> +            return .none
전략 패턴을 적용하는 방법으로 Step 파일을 도메인 마다 생성하기로 구상했습니다. 다만 현재 Step 파일을 나누고 연결하는 방법을 강구해야 할 것 같아 바로 적용은 어려울 것 같습니다. 추후 적용하겠습니다.

2024-04-28 11:13 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Base/BaseViewController.swift
> +
[76f9895] 수정한 커밋입니다.
해당 코드를 삭제하고나니 해당 파일이 현재 필요하지 않다 판단되어 삭제했습니다

2024-04-28 11:16 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/AppStep.swift
> +}
[732da77] 수정한 커밋입니다.

2024-04-28 11:17 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/AppFlow.swift
> +// MARK: 화면 이동 로직
[a76318d] 수정한 커밋입니다.

2024-04-28 11:17 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Main/ToDo/ToDoReactor.swift
> +    }
[a76318d] 수정한 커밋입니다.

2024-04-28 11:18 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/ToDoFlow.swift
> +import UIKit
[dc4b13f] 수정한 커밋입니다.

2024-04-28 11:21 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/ToDoFlow.swift
> +        guard let step = step as? AppStep else { return .none }
[e93bfb1] 수정한 커밋입니다.

2024-04-28 11:21 UTC, gguming commented on ToDoGeo/ToDoGeo/System/SceneDelegate.swift
> +        guard let windowScene = (scene as? UIWindowScene) else { return }
[e93bfb1] 수정한 커밋입니다.

2024-04-28 11:21 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/SignInFlow.swift
> +        guard let step = step as? AppStep else { return .none }
[e93bfb1] 수정한 커밋입니다.

2024-04-28 11:22 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/SignInFlow.swift
> +
[3f84dfe] 수정한 커밋입니다.

2024-04-28 11:23 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/SignInFlow.swift
> +        return viewController
[198f0f7] 수정한 커밋입니다.

2024-04-28 12:15 UTC, abdul0986 approved these changes
LGTM

2024-04-29 14:14 UTC, merged