#4 네트워크 레이어 구축
f-lab-edu/ToDoGeo pull request #8
Opened 2024-04-30 14:33 UTC by gguming

#4 네트워크 레이어 구축 관련 PR
네트워크 레이어는 Alamofire 라이브러리를 기반으로 합니다.

# Target
target에서는 URLRequest를 만들 재료를 받고, 쿼리, 바디, 쿼리와 파라미터 케이스에 따라 각 재료를 조합하여 URLRequest를 만드는 역할을 합니다.

# API
API에서는 target에서 만든 URLRequest를 Alamofire에서 API 호출 기능을 담당하는 DataRequest로 만드는 함수가 있습니다.

# NetworkEventLogger
Alamofire에서 제공하는 네트워크 로그 출력 기능을 커스텀했습니다.

# APIService
APIService는 실질적으로 API를 호출하는 함수 request가 있고, 호출이 설정된 Target 정보와 Response 타입을 받아 api 호출을 시도합니다.
내부에서는 RxSwift가 호환될 수 있도록 작업해 두었습니다.

![image](https://github.com/f-lab-edu/ToDoGeo/assets/72551674/80a93a21-c0ca-4d14-91e5-99dce6530798)

# 네트워크 시퀀스 다이어그램
네트워크의 흐름을 알 수 있도록 ReadMe 파일에 시퀀스 다이어그램을 추가했습니다.
<img width="1395" alt="image" src="https://github.com/f-lab-edu/ToDoGeo/assets/72551674/e5c28aa5-2724-4a24-9854-eee77919d595">

2024-05-06 06:53 UTC, abdul0986 requested changes

2024-05-06 06:53 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/API.swift
> +    }
함수의 이름이 역할과 어울리지 않습니다. 역할을 충분히 드러낼 수 있는 명칭으로 변경해주세요

2024-05-06 06:53 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/APIService.swift
> +    }
코드가 너무 깁니다. 코드 사이즈를 불이거나 분리하는 방법을 고민해주세요.

2024-05-06 06:53 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/NetworkEventLogger.swift
> +    var toPrettyPrintedString: String? {
변수명이 좀 Verbose한데요. 맨 뒤에 'XXXString'이 꼭 추가되어 있어야 할지??? 고민해주세요

2024-05-06 06:53 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/Target.swift
> +    }
함수가 너무 깁니다. 10줄 이내로 줄일 수 있도록, 분리할 수 있는 부분이 있을지 확인해주세요

2024-05-06 06:53 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/Target.swift
> +        urlRequest.setValue("application/json", forHTTPHeaderField: "Content-Type")
코드 내부에 인라인 리터럴이 들어가는 것은 좋지 않은 코드입니다. 리터럴은 가급적 외부로 빼 주세요

2024-05-06 06:53 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/Target.swift
> +            return Parameters()
현재 코드에서는 에러가 발생할 경우 디버그 로그를 출력하고 빈 Parameters를 반환하고 있는데요, 이 경우 에러가 발생한 이유가 내부에서 뭉게지므로, 에러 원인을 명확하게 파악하기 어려울 수 있습니다. 대신 에러를 던져서 호출자가 적절하게 처리할 수 있도록 하는 것이 더 좋습니다.

2024-05-06 06:53 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/Target.swift
> +}
1. 전체적으로 에러를 내부적으로 뭉게는 것은 디버깅을 어렵게 만듭니다. 
2. do ~ catch 코드의 범위가 커지면서 코드의 Depth가 길어지는 결과를 가져왔습니다. 
3. 에러 타입이 정의되어 있지 않습니다. 

이상의 이슈를 고려하여 위 코드는 이렇게 변경할 수 있습니다. 가독성 측면에서 어느 것이 더 나을지 고민해봐주세요 

```
extension Encodable {
    func toParameter() throws -> Parameters {
        let data = try JSONEncoder().encode(self)
        let jsonObject = try JSONSerialization.jsonObject(with: data, options: [])
        
        guard let parameter = jsonObject as? Parameters else {
            throw SerializationError.invalidParameter
            // 혹은 return Parameters() 
        }
        
        return parameter
    }
}

enum SerializationError: Error {
    case invalidParameter
}

```

2024-05-09 02:51 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/API.swift
> +    }
[24c1b5c] 수정된 커밋입니다.

2024-05-09 02:52 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/APIService.swift
> +    }
[14bff4b] 수정된 커밋입니다. response 처리 영역을 함수로 분리했습니다.

2024-05-09 02:58 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/NetworkEventLogger.swift
> +    var toPrettyPrintedString: String? {
[db8797d] 수정된 커밋입니다. printed라는 이름은 제외했으나 마지막에 String이 붙는것은 유지했습니다.
해당 프로퍼티는 Data영역에서 정보를 가공하여 String으로 리턴하는 기능을 가지고 있기 때문에 toXXXXString 형태로 이름을 가져가는것이 가독성과 직관성이 향상될것이라 판단했습니다.

2024-05-09 04:22 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/Target.swift
> +    }
[8a43a66] 수정된 커밋입니다.

- 해당 로직을 다시 살펴보다보니 query와 body의 case는 queryNBody case로 모두 커버거 가능할 것으로 판단되어 query, body case를 삭제했습니다.
- 쿼리 만드는 부분을 함수로 분리하고 body를 설정하는 소스를 간소화 했습니다.

2024-05-09 04:23 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/Target.swift
> +        urlRequest.setValue("application/json", forHTTPHeaderField: "Content-Type")
[8a43a66] 수정된 커밋입니다.
해당 부분은 삭제하고 외부에서 header를 추가하려고 합니다.

2024-05-09 04:24 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/Target.swift
> +}
[8a43a66] 수정된 커밋입니다.
말씀하신 부분에 동의하여 수정하였고, 해당 함수를 사용하는 부분 또한 에러를 리턴해야함에 따라 try 키워드를 추가했습니다.

2024-05-11 13:54 UTC, abdul0986 requested changes
변경하신 부분에 대한 추가 코멘트를 달았습니다. 확인해주세요

2024-05-11 13:54 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/API.swift
> +    static func requestToAlamofire(_ convertible: URLRequestConvertible, interceptor: RequestInterceptor? = nil) -> DataRequest {
잘 바꾸셨습니다만, API에서 `XXXAlamofire`는 지나치게 특정 라이브러리에 디펜던시를 가지는 메소드 명인 것 같습니다. 실제로 `Alamofire` 대신 다른 라이브러리를 사용하는 경우까지 고려해서 `requestToExternalAPI` 같은 게 어떻까 합니다.

2024-05-11 13:54 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/Target.swift
> +        }
내부에서 정의된 url과 parameter url이 같은 이름을 사용하지 않도록 해주세요. 굳이 내부의 변수를 `url`로 유지하고자 한다면 파라미터 측의 `url`은 Internal Parameter를 활용하여, 명확하게 구분되도록 처리해주세요.

2024-05-11 13:54 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/Target.swift
> +    var headers: [String: String] { get }
인라인 리터럴을 제거하기 위해 headers를 멤버 변수로 추가하신 것 같은데요, 살펴보니 headers는 `asURLRequest()`에서만 사용하고 있네요. 이 경우에는 굳이 멤버 변수로 등록하여 관리할 필요가 없습니다. 메소드의 파라미터로 입력받을 수 있도록 변경하시길 권장드립니다.

2024-05-11 14:56 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/Target.swift
> +    var headers: [String: String] { get }
인라인 리터럴 부분과 상관없이 처음에 추가해 놓은 상황이였습니다. 해당 부분은 Target을 준수하는 구현체가 생기면 해당 구현체에서 header의 정보를 주입하게 되어있습니다. 그래서 asURLReqeust 함수에서 인라인 리터럴로 header를 직접 주입하는것보다 target 구현체에서 header 정보를 주입하는것이 낫지 않을까해서 리터럴 부분만 지우게 되었습니다.

한편, 말씀하신 메소드의 파라미터로 header를 주입 받는 부분도 생각을 해보았는데요. 만약 그렇게 된다면 api 정보 중  header 정보는 request 함수로 나머지 정보는 target 구현체로 가게 되는데 이 정보가 분산 배치되어 추후 관리 하기가 어려워질것으로 생각이 들었습니다. 제가 문제라고 생각한 부분은 감안하고 넘어가도 괜찮을까요?

2024-05-11 14:58 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/Target.swift
> +        }
[b4c175a] 수정한 커밋입니다.

2024-05-11 14:59 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/API.swift
> +    static func requestToAlamofire(_ convertible: URLRequestConvertible, interceptor: RequestInterceptor? = nil) -> DataRequest {
[230b013] 수정한 커밋입니다.
함수 명칭에 대해 말씀해주신 범위까지 생각해보지 못했습니다. 알려주셔서 감사합니다.

2024-05-12 12:59 UTC, abdul0986 approved these changes
LGTM 수고하셨습니다.

2024-05-12 13:13 UTC, merged