[#6] 로그인 기능 PR
f-lab-edu/ToDoGeo pull request #9
Opened 2024-05-05 11:13 UTC by gguming

[#6] 로그인 관련 기능입니다.
![image](https://github.com/f-lab-edu/ToDoGeo/assets/72551674/814e9de6-43fe-4b2d-b9f5-08d149648aab)

# 이메일 로그인
- firebase에 대한 의존성을 추가하고 firebase의 인증 기능인 이메일 로그인 기능을 구현했습니다.
- SignInViewController에 이메일, 비밀번호 입력창과 로그인 버튼, 회원가입 버튼을 추가했습니다.
- SignInReactor에는 회원 가입에 필요한 로직을 작성했습니다.
- SignInReactorTests 에는 reactor에 추가된 기능에 대해 단위 테스트를 작성하였습니다.
- 로그인 성공 시 화면전환 로직을 reactor에 추가했습니다.

# 유의 사항
- 현재 Network 관련된 PR이 검토되지 않아 Firebase에 대한 로직은 reactor에 추가해 두었습니다.

2024-05-05 13:19 UTC, abdul0986 commented on ToDoGeo/ToDoGeoTests/ReactorTests/SignInReactorTests.swift
> +
삭제 해주세요

2024-05-06 06:08 UTC, abdul0986 commented
Issue에 UserStory 기반으로 AC(Acceptance Criteria)와 함께 작성해주세요~

2024-05-06 06:39 UTC, abdul0986 requested changes

2024-05-06 06:39 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/Flows/SignInFlow.swift
> +            return .end(forwardToParentFlowWithStep: AppStep.toDoRequired)
Empty Line 정책이 일관되지 않습니다. 29 라인은 공백이 들어갔는데 나머지 라인에는 공백이 없네요 일관되도록 Empty Line 정책을 적용해주세요

2024-05-06 06:39 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInReactor.swift
> +        var isEnableSignInButton: Bool = false
타입이 비교적 명확해서 굳이 Type Annotation을 할 필요가 없는 경우에는 가독성을 위해, 타입을 생략해주기를 권장합니다.

2024-05-06 06:39 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInReactor.swift
> +
Empty Line이 이상하게 적용되어 있습니다. 확인해주세요

2024-05-06 06:39 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInReactor.swift
> +            }
코드가 너무 깁니다. 별도의 서브 함수로 분리하는 것이 좋을 듯 합니다.

2024-05-06 06:39 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInReactor.swift
> +            if newState.isValidPassword == false {
이 구문을 해석하자면 아래와 같습니다. 
```
if false == false {
   ...
}
또는 
if true == false {
  ... 
}
```
이미 true / false인 Statement를 재비교하는 것은 불필요한 연산을 더하는 결과를 가져오기 때문에, 좋지 않은 코드입니다.

2024-05-06 06:39 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInReactor.swift
> +extension SignInReactor {
'MARK' 주석으로 구분해 줄 필요가 있어 보입니다.

2024-05-06 06:39 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInReactor.swift
> +        let emailRegEx = "[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}"
이메일과 패스워드 등의 유효성 체크를 위한 RegEx Literal 들이 등장하는데, 클래스 파일 내에서 Inline Literal이 들어가는 것은 좋지 않습니다. 별도의 파일로 빼거나, 혹은 외부 설정으로 처리할 수 있도록 해 주는 것이 좋겠습니다.

2024-05-06 06:39 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInReactor.swift
> +                print(error.debugDescription)
1. 로그인 실패 시에 그냥 출력만 해주고 끝인가요? 뭔가 처리가 더 있어야 하지 않을지.. 
2. 로깅을 위해서 `print()`를 사용하는 것은 좋지 않습니다. 아래를 참고해주세요  https://developer.apple.com/documentation/os/logger

2024-05-06 06:39 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInViewController.swift
> +    }
함수가 너무 깁니다. 함수가 긴 경우에는 대부분 SRP를 위배하게 됩니다. 10줄 이내로 함수를 작성할 수 있도록 분리해주세요.

2024-05-06 06:39 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInViewController.swift
> +        })
```suggestion
        [emailTextField, passwordTextField, signInButton, signUpButton].forEach {
            view.addSubview($0)
            $0.translatesAutoresizingMaskIntoConstraints = false
        }
```

2024-05-06 06:39 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInViewController.swift
> +
Verbose합니다. 가독성 및 최적화를 위해 Layout 라이브러리를 적용해주세요

2024-05-06 06:39 UTC, abdul0986 commented on ToDoGeo/ToDoGeoTests/ReactorTests/SignInReactorTests.swift
테스트 케이스를 주석으로 작성해서 명시해주세요

2024-05-10 06:56 UTC, gguming commented on ToDoGeo/ToDoGeoTests/ReactorTests/SignInReactorTests.swift
> +
삭제했습니다.

2024-05-10 06:56 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/Flows/SignInFlow.swift
> +            return .end(forwardToParentFlowWithStep: AppStep.toDoRequired)
[0e64a83] 수정된 커밋입니다.

2024-05-10 06:57 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInReactor.swift
> +        var isEnableSignInButton: Bool = false
[62d3071] 수정된 커밋입니다.

2024-05-10 06:58 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInReactor.swift
> +
[33d4d0c] 수정된 커밋입니다.

2024-05-10 06:59 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInReactor.swift
> +            }
[325022e] 수정된 커밋입니다.
로그인 버튼 활성화 체크 로직은 분리되는것이 맞다고 판단되어 해당 기능을 분리하여 mutation에 활성화를 체크하는 로직을 추가했습니다.

2024-05-10 07:00 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInReactor.swift
> +            if newState.isValidPassword == false {
해당 코드들 모두 수정했습니다.

2024-05-10 07:00 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInReactor.swift
> +extension SignInReactor {
[d027a33] 수정된 커밋입니다.

2024-05-10 07:01 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInReactor.swift
> +        let emailRegEx = "[A-Z0-9a-z._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}"
[a69730b] 정규식을 enum 내부에 상수로 추가했습니다.

2024-05-10 07:04 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInViewController.swift
> +    }
[89fd3be] 수정된 커밋입니다. action과 state의 binding을 함수로 분리하였습니다.

2024-05-10 07:05 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInViewController.swift
> +
[4992c56] pinlayout을 도입하여 수정하였습니다.

2024-05-10 07:05 UTC, gguming commented on ToDoGeo/ToDoGeoTests/ReactorTests/SignInReactorTests.swift
[50da22e] 주석 추가했습니다.

2024-05-11 14:07 UTC, abdul0986 requested changes
퀵하게 피드백 반영 부탁드립니다.

2024-05-11 14:07 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInReactor.swift
> +
51 line의 경우와 Empty Line 정책이 일관되지 않습니다. 통일해주세요.

2024-05-11 14:07 UTC, abdul0986 commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInViewController.swift
> +            .disposed(by: disposeBag)
`.bind`와 `.disposed`가 동일 반복되고 있는데, 간소화할 방법이 없을까요? 🤔
이를테면 `.bind`와 `.disposed`를 내부적으로 처리하도록 래핑된 구조체나 클래스를 정의하는 방법이요.

2024-05-11 14:07 UTC, abdul0986 commented on ToDoGeo/ToDoGeoTests/ReactorTests/SignInReactorTests.swift
> +    // email 유효성 관련 테스트(이메일 포맷이 아닐 때 유효성 체크 실패 케이스)
Example) 

`이메일에 'ggg'가 입력되면 이메일 포맷이 올바르지 않으므로 유효성 체크가 실패한다`라는 시나리오 방식으로 작성해주시는 것이 직관적이고 좋습니다.

2024-05-11 14:22 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInViewController.swift
> +            .disposed(by: disposeBag)
이 부분은 extension이나 말씀하신대로 구조체나 클래스로 정의하는 부분을 고민해보겠습니다.
다만 추후 조금 시간이 걸릴 것 같아 추후 리팩토링 사항으로 남겨둬도 괜찮을까요?

2024-05-11 14:24 UTC, gguming commented on ToDoGeo/ToDoGeo/Presenter/SignIn/SignInReactor.swift
> +
[ccf1734] 수정된 커밋입니다.

2024-05-11 14:24 UTC, gguming commented on ToDoGeo/ToDoGeoTests/ReactorTests/SignInReactorTests.swift
> +    // email 유효성 관련 테스트(이메일 포맷이 아닐 때 유효성 체크 실패 케이스)
[e95a121] 수정된 커밋입니다.

2024-05-12 12:56 UTC, abdul0986 commented on ToDoGeo/ToDoGeoTests/ReactorTests/SignInReactorTests.swift
> +    // email 유효성 관련 테스트(이메일이 정상 포맷일 떄 유효성 체크 성공 케이스)
```
// 정상적인 이메일이 입력되면 유효성 체크가 성공한다. 
```

2024-05-12 12:57 UTC, abdul0986 commented on ToDoGeo/ToDoGeoTests/ReactorTests/SignInReactorTests.swift
> +    // 비밀번호 유효성 관련 테스트(비밀번호가 비어있을 떄 유효성 체크 실패 케이스)
```
// 비밀번호가 비어 있으면 유효성 체크는 실패한다. 
```

2024-05-12 12:59 UTC, abdul0986 approved these changes
LGTM 수고하셨습니다.

2024-05-12 13:23 UTC, merged